# Generated by Django 4.2.4 on 2023-09-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_gallery_carbon_alter_gallery_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='carbon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='fat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='kcal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='pro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
