# Generated by Django 4.2.4 on 2023-09-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_gallery_carbon_alter_gallery_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='kcal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='pro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='carbon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='kcal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='pro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
